/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SkillsRegistry } from "./SkillsRegistry";
export * as factories from "./factories";
export { SkillsRegistry__factory } from "./factories/SkillsRegistry__factory";
